#服务器端口
server:
  port: 8102

#数据源配置
spring:
  datasource:
    url: ${kaleidoscope..datasource.dev.url}
    username: ${kaleidoscope.datasource.dev.username}
    password: ${kaleidoscope.datasource.dev.password}
