#服务器端口
server:
  port: 8105

#数据源配置
spring:
  datasource:
    url: ${kaleidoscope.datasource.dev.url}
    username: ${kaleidoscope.datasource.dev.username}
    password: ${kaleidoscope.datasource.dev.password}
