#服务器端口
server:
  port: 8200

#数据源配置
#spring:
#  datasource:
#    url: ${blade.datasource.dev.url}
#    username: ${blade.datasource.dev.username}
#    password: ${blade.datasource.dev.password}

spring:
  #排除DruidDataSourceAutoConfigure
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为master
      primary: master
      datasource:
        master:
          url: ${kaleidoscope.datasource.dev.url}
          username: ${kaleidoscope.datasource.dev.username}
          password: ${kaleidoscope.datasource.dev.password}
        slave:
          url: ${kaleidoscope.datasource.dev.url}
          username: ${kaleidoscope.datasource.dev.username}
          password: ${kaleidoscope.datasource.dev.password}

demo:
  name: "kaleiscopeDemoName"
